- name: automated
  description: This was created by a bot
  color: 2a2a2a
- name: bug
  description: Something isn't working as expected
  color: d73a4a
- name: data
  description: Static data and definitions
  color: c40ffb
- name: dependencies
  description: Updates to application dependency files
  color: 0366d6
- name: documentation
  description: Improvements or additions to documentation
  color: 0075ca
- name: dotfiles
  description: Configuration files for developer tools and CI/CD
  color: 39d5e1
- name: duplicate
  description: This issue or pull request already exists
  color: cfd3d7
- name: enhancement
  description: New features and feature requests
  color: a2eeef
- name: good first issue
  description: Issues well suited to new contributors
  color: 7057ff
- name: help wanted
  description: Extra attention or community insight is needed
  color: 999bc4
- name: question
  description: Further information is required
  color: 3081c8
- name: restricted
  description: Files not intended for public revision
  color: cc3333
- name: source code
  description: Updates to the application or library source code
  color: 33cc33
- name: specs
  description: Data definitions and shared types
  color: 10ec8b
- name: synchronize
  description: Synchronization of standard files shared across projects
  color: c2c456
- name: test code
  description: Updates to the application or library test code
  color: 3333cc
- name: tooling
  description: Repository tools, CI/CD jobs, automated actions
  color: 0052cc
- name: wontfix
  description: This will not be worked on
  color: ffffff
- name: clojure
  description: Clojure source code
  color: 5881d8
- name: clojurescript
  description: ClojureScript source code
  color: 91dc47
- name: javascript
  description: JavaScript source code
  color: d7f0a2

# This file was automatically copied and populated by rebroadcast
# Do not edit this file directly, instead modify the source at https://github.com/Wall-Brew-Co/rebroadcast/blob/master/sources/github-actions/labels.yml
