# Verifies that the project is compatible with cljdoc, and that our documentation will render correctly.
name: Check cljdoc compatibility

on: ["pull_request", "workflow_dispatch"]

jobs:
  check-cljdoc:

    # Cancel any runs in progress for the same workflow and PR
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    runs-on: ubuntu-latest
    steps:
      - name: Echo Trigger
        id: echo-trigger
        run: echo "Job triggered by ${{ github.event_name }}"

      - name: Echo Runner OS
        id: echo-runner-os
        run: echo "Job running on ${{ runner.os }} server"

      - name: Echo Git Ref
        id: echo-git-ref
        run: echo "Using ${{ github.ref }} branch from ${{ github.repository }} repository"

      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Java
        id: install-java
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'adopt'
          java-version: '21'
          # This should match system.properties

      - name: Install Leiningen
        id: install-leiningen
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          lein: 'latest'
          clj-kondo: 'latest'
          cljstyle: 'latest'

      - name: Cache Maven Dependencies
        id: cache-maven
        uses: actions/cache@v4
        env:
          cache-name: cache-maven
        with:
          path: ~/.m2
          key: ${{ runner.os }}-clj-${{ hashFiles('**/project.clj') }}
          restore-keys: |
            ${{ runner.os }}-clj

      - name: Install Clojure Dependencies
        id: install-deps
        run: lein deps

      - name: Echo Leiningen Version
        id: lein-version
        run: lein -v

      - name: Package The Library As A Jar
        id: package
        run: lein jar

      - name: cljdoc Check
        id: cljdoc-check
        uses: cljdoc/cljdoc-check-action@v0.0.3

      - name: Echo Status
        id: echo-status
        run: echo "Job status is ${{ job.status }}."

# This file was automatically copied and populated by rebroadcast
# Do not edit this file directly, instead modify the source at https://github.com/Wall-Brew-Co/rebroadcast/blob/master/sources/github-actions/workflows/cljdoc_test.yml
