name: Clojure Dependency Update

on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v3.0.2

    - name: Check deps
      uses: nnichols/leiningen-dependency-update-action@v1
      with:
        github-token: ${{ secrets.WALL_BREW_BOT_PAT }}
        git-email: the.wall.brew@gmail.com
        git-username: WallBrewBot
        skips: "pom"
