# Automatically generate TODO Issues from source code comments
name: Generate TODO Tickets

on:
  push:
    branches:
    - master

jobs:
  todo:

    runs-on: ubuntu-latest

    steps:
      - name: Echo Trigger
        id: echo-trigger
        run: echo "Job triggered by ${{ github.event_name }}"

      - name: Echo Runner OS
        id: echo-runner-os
        run: echo "Job running on ${{ runner.os }} server"

      - name: Echo Git Ref
        id: echo-git-ref
        run: echo "Using ${{ github.ref }} branch from ${{ github.repository }} repository"

      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4.2.2

      - name: Generate TODO Tickets
        id: todo
        uses: ribtoks/tdg-github-action@master
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}
          LABEL: "TODO"
          ROOT: "src"
          # This is scoped to /src to prevent accidental discovery of comments in node_modules, git hooks, etc.

      - name: Echo Status
        id: echo-status
        run: echo "Job status is ${{ job.status }}."

# This file was automatically copied and populated by rebroadcast
# Do not edit this file directly, instead modify the source at https://github.com/Wall-Brew-Co/rebroadcast/blob/master/sources/github-actions/workflows/todo.yml
